service: arquitecturaUAI

provider:
  name: aws
  profile: nico
  runtime: nodejs6.10
  memorySize: 256

functions:
  getData:
    handler: handler.getData
    events:
      - http:
          path: api/getData
          method: get
          cors: true
  newData:
    handler: handler.newData
    events:
      - http:
          path: api/newData
          method: post
          cors: true
